# Generated by Django 5.0.7 on 2024-07-28 02:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='solde_a_retirer',
        ),
        migrations.RemoveField(
            model_name='client',
            name='solde_depot',
        ),
        migrations.AddField(
            model_name='client',
            name='connecter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='tatchumkamgajordandouglas@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(default='333', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_inscription',
            field=models.DateTimeField(default=datetime.date(2024, 7, 28)),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(default='nom', max_length=200),
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_deposer', models.IntegerField()),
                ('solde_a_retirer', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
