# Generated by Django 5.0.7 on 2024-07-31 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_solde_a_retirer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 17, 8, 21, 159873, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='compte',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='compte',
            name='solde_a_retirer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compte',
            name='solde_deposer',
            field=models.IntegerField(default=0),
        ),
    ]
