# Generated by Django 5.0.7 on 2024-08-01 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_date_inscription_alter_compte_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(null=True, upload_to='public'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 15, 8, 2, 532906, tzinfo=datetime.timezone.utc)),
        ),
    ]
