# Generated by Django 5.0.7 on 2024-08-01 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_date_inscription_alter_machine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='delai',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 19, 8, 55, 540603, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 19, 8, 55, 536606, tzinfo=datetime.timezone.utc)),
        ),
    ]
