# Generated by Django 5.0.7 on 2024-08-03 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_achat_prochain_minage_alter_achat_delai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minage',
            name='client',
        ),
        migrations.AlterField(
            model_name='achat',
            name='delai',
            field=models.DateField(default=datetime.datetime(2024, 8, 3, 18, 21, 38, 91048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='achat',
            name='prochain_minage',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 18, 21, 38, 91048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2024, 8, 3, 18, 21, 38, 89045, tzinfo=datetime.timezone.utc)),
        ),
    ]
